" Tim Child's Vim setup
" project.vim is installed
" Submodules used:
"
" git submodule add git://github.com/tpope/vim-fugitive.git files/vim/bundle/fugitive.vim
" git submodule add git://github.com/sjl/gundo.vim files/vim/bundle/gundo.vim
" git submodule add git://github.com/scrooloose/nerdtree.git files/vim/bundle/nerdtree.vim 
" git submodule add git://github.com/kien/ctrlp.vim.git files/vim/bundle/ctrlp.vim
" git submodule add http://github.com/bingaman/vim-sparkup.git files/vim/bundle/vim-sparkup    
" git submodule add https://github.com/groenewege/vim-less.git files/vim/bundle/vim-less 
" 
" Start Pathogen
call pathogen#infect()

" History is 1000 lines
set history=1000

" Set tabs at 4 spaces
set tabstop=4
set shiftwidth=4
set softtabstop=4
" use spaces instead of tabs
set expandtab
set autoindent
set smartindent
set smarttab

" Set the leader character to something sensible
let mapleader = ","
let g:mapleader = ","

" Enable filetype plugins
filetype plugin on
filetype indent on
filetype on
syntax on

" Ignore these files
set wildignore=*.swp,*.bak,*.pyc
let NERDTreeIgnore = ['\.pyc$']

" Set to auto read when a file is changed from the outside
set autoread

"""""""""""""""""""""""""""""""""""""""""""""""""""
" VIM UI
"""""""""""""""""""""""""""""""""""""""""""""""""""
" Set 7 lines to the cursor - when moving vertically using j/k so there is
" always something above or below
set so=7

" Turn on the WiLd menu for buffer exploration ( :b <Tab> ) and explorer ( :e <Tab> )
set wildmenu

" Set the numbers always on
set nu

" Always show the rules
set ruler

" Show matching brackets when text indicator is over them
set showmatch

" How many tenths of a second to blink when matching brackets
set mat=2

" Use visualbell instead of the nasty sound
set visualbell
set textwidth=0
set wrapmargin=0
set tw=0

" disable arrow keys
"map <up> <nop>
"map <down> <nop>
"map <left> <nop>
"map <right> <nop>
"imap <up> <nop>
"imap <down> <nop>
"imap <left> <nop>
"imap <right> <nop>


"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Misc
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Remove the Windows ^M - when the encodings gets messed up
noremap <Leader>m mmHmt:%s/<C-V><cr>//ge<cr>'tzt'm

" Toggle paste mode on and off
map <leader>pp :setlocal paste!<cr>

" Return to last edit position when opening files (You want this!)
autocmd BufReadPost *
     \ if line("'\"") > 0 && line("'\"") <= line("$") |
     \   exe "normal! g`\"" |
     \ endif
" Remember info about open buffers on close
set viminfo^=%



"""""""""""""""""""""""""""""""""""""""""""""""""""
" Colors
"""""""""""""""""""""""""""""""""""""""""""""""""""
" set extra options when running in GUI mode
if has("gui_running")
    set guioptions-=T
    set guioptions+=e
    set t_Co=256
    set guitablabel=%M\ %t
endif


" Swap files create in temporary directories instead of the local directory
set backup 
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp 
set backupskip=/tmp/*,/private/tmp/* 
set directory=~/.vim-tmp,~/.tmp,~/tmp,/var/tmp,/tmp 
set writebackup

au BufNewFile,BufRead *.less set filetype=less
au BufNewFile,BufRead *.js set filetype=javascript.javascript-jquery
au BufNewFile,BufRead *.html set filetype=html.javascript.javascript-jquery
au BufNewFile,BufRead *.py set filetype=python
autocmd FileType python set omnifunc=pythoncomplete#Complete

" NERDTree setup
" Fix the width of NERDTree.
" Map NERDTreeToggle to convenient key
let g:NERDTreeWinSize = 48 
nmap <leader>n :NERDTreeToggle<cr>

