# This configuration file assumes that you have the following installed:
#  - Git
#  - django
#  - brew (though it might work without it).
#  - virtualenv
#  - virtualenvwrapper
#
# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Looks in ~/.oh-my-zsh/themes/
ZSH_THEME="oh-matron"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"
export git=/usr/local/git/bin/git
# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git django brew github ssh-agent)

export SVN_EDITOR=vim
export EDITOR=vim
export WORKON_HOME=~/.virtualenvs

# Check for virtual wrapper before trying to start using it.
if [ -f "/usr/local/bin/virtualenvwrapper.sh" ]
then
    export VIRTUALENVWRAPPER_LOG_DIR="$WORKON_HOME"
    export VIRTUALENVWRAPPER_HOOK_DIR="$WORKON_HOME"
    source /usr/local/bin/virtualenvwrapper.sh
fi
source $ZSH/oh-my-zsh.sh
export VIRTUAL_ENV_DISABLE_PROMPT="True"

# Private includes (which should include your path)
if [[ -r ~/.privateinclude ]]; then
     source ~/.privateinclude
fi

# MVim has python references and other nicities. -v starts it in the terminal.
if [ -f "/usr/local/bin/mvim" ]
then 
   alias vim="mvim -v"
fi
